# Generated by Django 4.1.2 on 2023-07-29 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slave', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='link_list',
            fields=[
                ('l_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=100)),
                ('u_id', models.ForeignKey(db_column='u_id', on_delete=django.db.models.deletion.CASCADE, to='slave.users')),
            ],
        ),
    ]
