# Generated by Django 4.1.2 on 2023-07-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slave', '0002_link_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='link_list',
            name='remark',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
